use_frameworks!

platform :ios, '8.0'

target 'AlivcVoiceCallSoloClient' do
  pod 'AlivcVoiceCallSolo', :path => './AlivcVoiceCallSolo'
  pod 'AliRTCSdk',:git=>'https://github.com/aliyunvideo/AliRtcSDK_iOS.git',:tag=>'1.17.2'
end
